// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuhdfgifopgqvrwpeuse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1aGRmZ2lmb3BncXZyd3BldXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTQ2MTcsImV4cCI6MjA2ODgzMDYxN30.Xtf8dGK2Bne9CnZVsKPiELQ5tiEizso3WWgpN7xOrMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});